### PR TITLE
Front end is disabled by default in recent version

### PR DESCRIPTION
**Pull request by naveen17797**
disable_front_end is set to false by default.

### CODE REVIEW

**Comment by Maikuolan** [comment]
Oops.. Cheers; Good catch. :+1:

**Comment by Maikuolan** [comment]
Ugh.. Actually, I shouldn't have merged this. Current documentation was correct; I misread when checking over the PR (distracted..? tired..? I don't know, but no worries; it can be easily fixed). Probably the same at your end, when writing the PR, I guess.

Current logic is that the front-end will only be enabled, when that directive is set to `false` (because the directive is to disable the front-end, rather than to enable it). So, the front-end is disabled by default, because the directive is set to `true` by default.

I wonder if this might be something worth changing for __[v3](https://github.com/CIDRAM/CIDRAM/issues/139)__ though? Probably, the misunderstanding was caused by using a positive to enforce a negative (setting to `false` to enable something), or a negative to enforce a positive (setting to `true` to disable something). Using a negative-negative/positive-positive logic, instead of positive-negative/negative-positive logic, might be more intuitive (and therefore less prone to being misread).

**Comment by naveen17797** [comment]
Oops sorry, installed it today and this striked my brain, i got confused and assumed disable_frontend as just frontend and thought documentation was wrong,  sorry :( 
Can you check your messenger?

**Comment by Maikuolan** [comment]
No problem at all; We did something similar here anyway (and time to make myself another coffee, I think). Anyway, even though the documentation was correct, I think we've discovered a counter-intuitive aspect to CIDRAM here, too (and also because, for me, the best way to recover from a *faux pas* like this, I think, is to find a way to spin it into something productive and good, haha). So, we'll work on this for v3 anyway. :-)

**Comment by naveen17797** [comment]
I need some help with the proposed feature : real time log viewer, i was trying to find the log file seems like blocked ips are logged, i didnt know how to block my ip , i was using CIDRAM in localhost,  i need some error log data for building the log viewer

**Comment by Maikuolan** [comment]
Cool cool. I'll reply at that issue there.

**Comment by Maikuolan** [comment]
(And fixed via rebase).

**Comment by DanielRuf** [comment]
Why not just do a revert? Please do not rebase / force-push on master =)

**Pull request merged**
